"""day11: debug reports

Revision ID: 3a765e256235
Revises: a95c416ffdab
Create Date: 2026-10-07 07:39:37.053840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3a765e256235'
down_revision: Union[str, None] = 'a95c416ffdab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('debug_reports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('call_id', sa.String(length=36), nullable=True),
    sa.Column('evaluation_result_id', sa.String(length=36), nullable=True),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('stage', sa.String(length=40), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('root_cause', sa.Text(), nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('recommendation', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_debug_reports_call_id'), 'debug_reports', ['call_id'], unique=False)
    op.create_index(op.f('ix_debug_reports_evaluation_result_id'), 'debug_reports', ['evaluation_result_id'], unique=False)
    op.create_index(op.f('ix_debug_reports_tenant_id'), 'debug_reports', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_debug_reports_tenant_id'), table_name='debug_reports')
    op.drop_index(op.f('ix_debug_reports_evaluation_result_id'), table_name='debug_reports')
    op.drop_index(op.f('ix_debug_reports_call_id'), table_name='debug_reports')
    op.drop_table('debug_reports')
    # ### end Alembic commands ###
