"""day9: add traces.call_id

Revision ID: a841f809ff32
Revises: 3b7ac2e54d90
Create Date: 2026-10-05 15:06:18.454001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a841f809ff32'
down_revision: Union[str, None] = '3b7ac2e54d90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('traces', sa.Column('call_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_traces_call_id'), 'traces', ['call_id'], unique=False)
    op.create_foreign_key(None, 'traces', 'calls', ['call_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'traces', type_='foreignkey')
    op.drop_index(op.f('ix_traces_call_id'), table_name='traces')
    op.drop_column('traces', 'call_id')
    # ### end Alembic commands ###
